version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "9997:80"
    depends_on:
      - react-app
