version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine  # Use the official Nginx image from Docker Hub
    ports:
      - "9998:80"
    depends_on:
      - react-app
