
# Use an official NGINX image as a base
FROM nginx:alpine

# Copy custom NGINX configuration file
COPY default.conf /etc/nginx/conf.d/default.conf

# Copy the build files from the ReactJS app
COPY --from=build /app/build /usr/share/nginx/html

# Expose the default NGINX port
EXPOSE 80
