version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
     volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9996:80"
    depends_on:
      - react-app
