FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom Nginx configuration file
COPY nginx/default.conf /etc/nginx/conf.d/

# Copy the built React app files into the Nginx HTML directory
COPY build/ /usr/share/nginx/html/

# Expose port 80 to the Docker host, so it can be accessed from outside the container
EXPOSE 80

# Command to run the Nginx server
CMD ["nginx", "-g", "daemon off;"]
