name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.react
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-reactjs-app:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-reactjs-app:${{ github.sha }}
